In [3]:
!pip install feature_engine
import pandas as pd
model_df = pd.read_pickle("model_churn_rf.pkl")
model_df

Collecting feature_engine
  Downloading feature_engine-1.9.4-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: numpy>=1.18.2 in /usr/local/lib/python3.13/dist-packages (from feature_engine) (2.1.3)
Requirement already satisfied: pandas>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from feature_engine) (2.2.3)
Requirement already satisfied: scikit-learn>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from feature_engine) (1.6.1)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.13/dist-packages (from feature_engine) (1.16.3)
Requirement already satisfied: statsmodels>=0.11.1 in /usr/local/lib/python3.13/dist-packages (from feature_engine) (0.15.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas>=2.2.0->feature_engine) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas>=2.2.0->feature_engine) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas>=2.2.0->feature_engine) (2026.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.4.0->feature_engine) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.4.0->feature_engine) (3.6.0)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.13/dist-packages (from statsmodels>=0.11.1->feature_engine) (1.0.3)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.13/dist-packages (from statsmodels>=0.11.1->feature_engine) (26.3)
Requirement already satisfied: formulaic>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from statsmodels>=0.11.1->feature_engine) (1.2.2)
Requirement already satisfied: interface-meta>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels>=0.11.1->feature_engine) (2.0.1)
Requirement already satisfied: narwhals>=1.17 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels>=0.11.1->feature_engine) (2.25.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels>=0.11.1->feature_engine) (4.16.0)
Requirement already satisfied: wrapt>=1.17.0rc1 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels>=0.11.1->feature_engine) (2.4.0)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.2.0->scikit-learn>=1.4.0->feature_engine) (3.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas>=2.2.0->feature_engine) (1.17.0)
Downloading feature_engine-1.9.4-py3-none-any.whl (243 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 243.5/243.5 kB 3.1 MB/s eta 0:00:00
Installing collected packages: feature_engine
Successfully installed feature_engine-1.9.4

model       (DecisionTreeDiscretiser(regression=False,\n  ...
features    [qtdeDiasD14, propAvgQtdeDias, qtdeDiasUltimaT...
dtype: object

In [4]:
df = pd.read_csv("/content/abt_churn.csv")
df.head()

,dtRef,idUsuario,qtdeTransacoes,qtdeDias,mediaTransacoesDias,saldoPontos,qtdePontosPos,qtdePontosNeg,qtdeDiasUltimaTransacao,qtdeDiasPrimeiraTransacao,...,saldoPontosD28,qtdePontosPosD28,qtdePontosNegD28,propAvgQtdeTransacoes,propAvgQtdeDias,propAvgMediaTransacoesDias,propAvgSaldoPontos,propAvgQtdePontosPos,propAvgQtdePontosNeg,flagChurn
0,2024-06-01,000ff655-fa9f-4baa-a108-47f581ec52a1,266,27,9.851852,635,2635,-2000,1.0,89.0,...,151,151,0,3.889781,3.278281,2.135602,1.516314,4.101926,8.944444,1
1,2024-10-01,000ff655-fa9f-4baa-a108-47f581ec52a1,268,28,9.571429,686,2686,-2000,4.0,211.0,...,51,51,0,3.309865,2.567615,2.328737,1.288278,2.920954,5.167037,1
2,2024-04-01,000ff655-fa9f-4baa-a108-47f581ec52a1,188,11,17.090909,275,1275,-1000,3.0,28.0,...,275,1275,-1000,3.805468,1.820201,3.739048,0.798622,2.634551,7.162791,0
3,2024-05-01,000ff655-fa9f-4baa-a108-47f581ec52a1,262,24,10.916667,484,2484,-2000,2.0,58.0,...,107,1107,-1000,4.246216,3.255244,2.322640,1.275749,4.275765,9.922414,0
4,2024-08-01,001749bd-37b5-4b1e-8111-f9fbba90f530,1,1,1.000000,50,50,0,21.0,21.0,...,50,50,0,0.013317,0.103973,0.236635,0.104533,0.063302,0.000000,1

In [10]:
amostra = df[df['dtRef']== df['dtRef'].max()].sample(5)

amostra

,dtRef,idUsuario,qtdeTransacoes,qtdeDias,mediaTransacoesDias,saldoPontos,qtdePontosPos,qtdePontosNeg,qtdeDiasUltimaTransacao,qtdeDiasPrimeiraTransacao,...,saldoPontosD28,qtdePontosPosD28,qtdePontosNegD28,propAvgQtdeTransacoes,propAvgQtdeDias,propAvgMediaTransacoesDias,propAvgSaldoPontos,propAvgQtdePontosPos,propAvgQtdePontosNeg,flagChurn
5309,2025-04-01,f48aa032-94dc-4d0f-9b0f-7f61d5f913cf,2,1,2.000000,2,2,0,22.0,22.0,...,2,2,0,0.024555,0.084922,0.505825,0.003862,0.002121,0.000000,1
990,2025-04-01,24782f0b-4683-4f35-976a-ea21d6714ba6,6904,254,27.181102,4419,27319,-22900,1.0,425.0,...,1165,1165,0,84.763703,21.570303,6.874447,8.532967,28.972528,53.875521,0
1040,2025-04-01,268ed8e7-3c04-4865-8594-8d0254954a35,1,1,1.000000,50,50,0,7.0,7.0,...,50,50,0,0.012277,0.084922,0.252913,0.096549,0.053026,0.000000,0
1684,2025-04-01,433a5751-70f6-4329-be50-dccc1002c00d,10,5,2.000000,206,206,0,1.0,39.0,...,101,101,0,0.122775,0.424612,0.505825,0.397780,0.218468,0.000000,0
2962,2025-04-01,7ee76b50-8c0e-4b8a-8fc6-5ce47d826e86,1,1,1.000000,50,50,0,21.0,21.0,...,50,50,0,0.012277,0.084922,0.252913,0.096549,0.053026,0.000000,1

In [12]:
model = model_df['model']
features = model_df['features']
predicao = model.predict_proba(amostra[features])[:,1]
amostra['probabilidade_churn'] = predicao
amostra

,dtRef,idUsuario,qtdeTransacoes,qtdeDias,mediaTransacoesDias,saldoPontos,qtdePontosPos,qtdePontosNeg,qtdeDiasUltimaTransacao,qtdeDiasPrimeiraTransacao,...,qtdePontosPosD28,qtdePontosNegD28,propAvgQtdeTransacoes,propAvgQtdeDias,propAvgMediaTransacoesDias,propAvgSaldoPontos,propAvgQtdePontosPos,propAvgQtdePontosNeg,flagChurn,probabilidade_churn
5309,2025-04-01,f48aa032-94dc-4d0f-9b0f-7f61d5f913cf,2,1,2.000000,2,2,0,22.0,22.0,...,2,0,0.024555,0.084922,0.505825,0.003862,0.002121,0.000000,1,0.846691
990,2025-04-01,24782f0b-4683-4f35-976a-ea21d6714ba6,6904,254,27.181102,4419,27319,-22900,1.0,425.0,...,1165,0,84.763703,21.570303,6.874447,8.532967,28.972528,53.875521,0,0.002953
1040,2025-04-01,268ed8e7-3c04-4865-8594-8d0254954a35,1,1,1.000000,50,50,0,7.0,7.0,...,50,0,0.012277,0.084922,0.252913,0.096549,0.053026,0.000000,0,0.707070
1684,2025-04-01,433a5751-70f6-4329-be50-dccc1002c00d,10,5,2.000000,206,206,0,1.0,39.0,...,101,0,0.122775,0.424612,0.505825,0.397780,0.218468,0.000000,0,0.360061
2962,2025-04-01,7ee76b50-8c0e-4b8a-8fc6-5ce47d826e86,1,1,1.000000,50,50,0,21.0,21.0,...,50,0,0.012277,0.084922,0.252913,0.096549,0.053026,0.000000,1,0.830494